// <auto-generated />
using System;
using BBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BBooking.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BBooking.Models.Entities.CasaVacanze", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HostId")
                        .HasColumnType("int");

                    b.Property<int>("LocalitaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrezzoPerNotte")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.HasIndex("LocalitaId");

                    b.ToTable("CaseVacanze");
                });

            modelBuilder.Entity("BBooking.Models.Entities.Localita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Localita");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Roma",
                            Regione = "Lazio"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Napoli",
                            Regione = "Campania"
                        });
                });

            modelBuilder.Entity("BBooking.Models.Entities.Prenotazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CasaVacanzeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<decimal>("Totale")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CasaVacanzeId");

                    b.HasIndex("GuestId");

                    b.ToTable("Prenotazioni");
                });

            modelBuilder.Entity("BBooking.Models.Entities.Servizio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Servizi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Wi-Fi"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Piscina"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Aria Condizionata"
                        });
                });

            modelBuilder.Entity("BBooking.Models.Entities.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ruolo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Utenti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@bbooking.com",
                            Nome = "Admin",
                            Password = "Admin123",
                            Ruolo = 2
                        },
                        new
                        {
                            Id = 2,
                            Email = "host@bbooking.com",
                            Nome = "Host",
                            Password = "Host123",
                            Ruolo = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "guest@bbooking.com",
                            Nome = "Guest",
                            Password = "Guest123",
                            Ruolo = 0
                        });
                });

            modelBuilder.Entity("CasaVacanzeServizio", b =>
                {
                    b.Property<int>("CaseVacanzeId")
                        .HasColumnType("int");

                    b.Property<int>("ServiziId")
                        .HasColumnType("int");

                    b.HasKey("CaseVacanzeId", "ServiziId");

                    b.HasIndex("ServiziId");

                    b.ToTable("CasaVacanzeServizio");
                });

            modelBuilder.Entity("BBooking.Models.Entities.CasaVacanze", b =>
                {
                    b.HasOne("BBooking.Models.Entities.Utente", "Host")
                        .WithMany("CaseOspitate")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BBooking.Models.Entities.Localita", "Localita")
                        .WithMany("CaseVacanze")
                        .HasForeignKey("LocalitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");

                    b.Navigation("Localita");
                });

            modelBuilder.Entity("BBooking.Models.Entities.Prenotazione", b =>
                {
                    b.HasOne("BBooking.Models.Entities.CasaVacanze", "CasaVacanze")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("CasaVacanzeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BBooking.Models.Entities.Utente", "Guest")
                        .WithMany("PrenotazioniEffettuate")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CasaVacanze");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("CasaVacanzeServizio", b =>
                {
                    b.HasOne("BBooking.Models.Entities.CasaVacanze", null)
                        .WithMany()
                        .HasForeignKey("CaseVacanzeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BBooking.Models.Entities.Servizio", null)
                        .WithMany()
                        .HasForeignKey("ServiziId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BBooking.Models.Entities.CasaVacanze", b =>
                {
                    b.Navigation("Prenotazioni");
                });

            modelBuilder.Entity("BBooking.Models.Entities.Localita", b =>
                {
                    b.Navigation("CaseVacanze");
                });

            modelBuilder.Entity("BBooking.Models.Entities.Utente", b =>
                {
                    b.Navigation("CaseOspitate");

                    b.Navigation("PrenotazioniEffettuate");
                });
#pragma warning restore 612, 618
        }
    }
}
